 <div class="panel panel-primary"> <table> <thead> <tr> <th scope="col"><?php echo app('translator')->getFromJson('Product'); ?></th> <th scope="col"><?php echo app('translator')->getFromJson('Unit Price'); ?></th> <th scope="col"><?php echo app('translator')->getFromJson('Quantity'); ?></th> <th scope="col"><?php echo app('translator')->getFromJson('Unit Tax (%)'); ?></th> <th scope="col"><?php echo app('translator')->getFromJson('Total'); ?></th> </tr> </thead> <tbody> <?php $__currentLoopData = $cartItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cartItem): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <tr> <td> <a target="_blank" href="<?php echo e(route('front.product.show', [$cartItem->options->slug])); ?>" class="thumbnail text-center"> <?php if($cartItem->options->has('photo')): ?> <?php if($cartItem->options->photo): ?> <?php
                                    $image_url = \App\Helpers\Helper::check_image_avatar($cartItem->options->photo, 150);
                                ?> <div class="img-box"> <img class="product-image" width="150" src="<?php echo e($image_url); ?>" alt="<?php echo e($cartItem->name); ?>" /> </div> <?php else: ?> <div class="img-box"> <img src="https://via.placeholder.com/150x150?text=No+Image" class="product-image" width="150" alt="<?php echo e($cartItem->name); ?>" /> </div> <?php endif; ?> <?php endif; ?> <h5 class="custom_cart_h5"><strong><?php echo e($cartItem->name); ?></strong> <?php if(is_array($cartItem->options->spec) && count($cartItem->options->spec)): ?> <br> <?php $__currentLoopData = $cartItem->options->spec; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $spec): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <b><?php echo e($spec['name']); ?>:</b> <?php echo e($spec['value']); ?><?php if(!$loop->last): ?><br> <?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php endif; ?> </h5> </a> </td> <td data-label="<?php echo app('translator')->getFromJson('Unit Price'); ?>"><?php echo e(currency_format($cartItem->options->unit_price)); ?></td> <td data-label="<?php echo app('translator')->getFromJson('Quantity'); ?>"> <?php echo e($cartItem->qty); ?> </td> <td data-label="<?php echo app('translator')->getFromJson('Unit Tax (%)'); ?>"><?php echo e($cartItem->options->unit_tax); ?></td> <td data-label="Total"><?php echo e(currency_format($cartItem->total)); ?></td> </tr> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> </tbody> <tfoot> <tr> <th></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo app('translator')->getFromJson('Products'); ?> </span></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(Cart::count()); ?> </span></th> </tr> <tr> <th></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo app('translator')->getFromJson('Sub Total'); ?> </span></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(currency_format(Cart::total())); ?> </span></th> </tr> <tr> <th></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo app('translator')->getFromJson('Tax'); ?> </span></th> <th class="ftr-cart-row" colspan="2"><span> + <?php echo e(config('settings.tax_rate')); ?> % </span></th> </tr> <tr> <th></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo app('translator')->getFromJson('Shipping Cost'); ?> </span></th> <?php if(config('settings.shipping_cost_valid_below') > Cart::total()): ?> <th class="ftr-cart-row" colspan="2"><span><?php echo e(currency_format(config('settings.shipping_cost'))); ?> </span></th> <?php else: ?> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(currency_format(0)); ?> </span></th> <?php endif; ?> </tr> <?php $cal_wallet_amount = 0; ?> <?php if(config('wallet.enable')): ?> <tr> <th></th> <?php
                $available_wallet_bal   = Auth::user()->walletBalance();
                $cal_wallet_amount  = $using_wallet_amount    = (Cart::total() * (int)(config('wallet.percent')))/100;
            ?> <?php if($available_wallet_bal >= $cal_wallet_amount): ?> <?php if(session()->has('wallet_used') && session()->get('wallet_used') == 1): ?> <?php
                        $left_wallet_bal        = $available_wallet_bal - $cal_wallet_amount;
                        $wallet_text            = 'Left Wallet balance :';
                        $checked                = 'checked';
                    ?> <?php else: ?> <?php
                        $cal_wallet_amount      = 0;
                        $left_wallet_bal        = $available_wallet_bal;
                        $wallet_text            = 'Wallet balance :';
                        $checked                = '';
                    ?> <?php endif; ?> <?php $checkbox                  = '<input type="checkbox" id="wallet_use" data-id="'.$using_wallet_amount.'" onchange="updateWalletUse()" '.$checked.'/> '; ?> <?php elseif($available_wallet_bal < $cal_wallet_amount): ?> <?php
                    $cal_wallet_amount      = 0;
                    $left_wallet_bal        = $available_wallet_bal;
                    $wallet_text            = 'Insufficient balance :';
                    $checked                = '';
                    $checkbox               = '<input type="checkbox" disabled'.$checked.'/> ';
                ?> <?php endif; ?> <th class="ftr-cart-row" colspan="2"><span> <?= $checkbox ?><?php echo app('translator')->getFromJson('Wallet Used'); ?><br> <small> ( <?php echo app('translator')->getFromJson($wallet_text); ?> <?php echo e(currency_format($left_wallet_bal,config('currency.default'))); ?> )</small></span> </th> <th class="ftr-cart-row" colspan="2"> <span> - <?php echo e(currency_format($cal_wallet_amount,config('currency.default'))); ?> </span></th> </tr> <?php endif; ?> <?php if(session()->has('coupon_amount') && session()->has('coupon_valid_above_amount') && session('coupon_valid_above_amount') < Cart::total()): ?> <tr> <th></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo app('translator')->getFromJson('Coupon Amount'); ?> </span></th> <th class="ftr-cart-row" colspan="2"><span> - <?php echo e(currency_format(session('coupon_amount'))); ?> </span> </th> </tr> <?php endif; ?> <tr> <th></th> <th class="ftr-cart-row" colspan="2"><span> <?php echo app('translator')->getFromJson('Total'); ?> </span></th> <?php if(config('settings.shipping_cost_valid_below') > Cart::total() && session()->has('coupon_amount') && session()->has('coupon_valid_above_amount') && session('coupon_valid_above_amount') < Cart::total()): ?> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(currency_format( config('settings.shipping_cost') - $cal_wallet_amount + Cart::total() - session('coupon_amount') + (Cart::total() * config('settings.tax_rate')) / 100)); ?> </span></th> <?php elseif(session()->has('coupon_amount') && session()->has('coupon_valid_above_amount') && session('coupon_valid_above_amount') < Cart::total()): ?> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(currency_format( Cart::total() - session('coupon_amount') - $cal_wallet_amount + (Cart::total() * config('settings.tax_rate')) / 100)); ?> </span></th> <?php elseif(config('settings.shipping_cost_valid_below') > Cart::total()): ?> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(currency_format(config('settings.shipping_cost') + Cart::total() - $cal_wallet_amount + (Cart::total() * config('settings.tax_rate')) / 100)); ?> </span></th> <?php else: ?> <th class="ftr-cart-row" colspan="2"><span> <?php echo e(currency_format(Cart::total() - $cal_wallet_amount + (Cart::total() * config('settings.tax_rate')) / 100)); ?> </span></th> <?php endif; ?> </tr> </tfoot> </table> </div>