 <div class="panel panel-default"> <div class="panel-body"> <div class="row"> <a style="margin-left:13px;" href="<?php echo e(route('manage.number_of_products.export_style_csv')); ?>" id="StyleCSV" class="btn btn-primary"><?php echo app('translator')->getFromJson('Export CSV'); ?></a> </div> <div class="table-responsive mt-15"> <?php if(!empty($root_categories)): ?> <?php 
                        $i = 1;
                        $totalProduct = 0;
                    ?> <table class="display table table-striped table-bordered table-hover viewStyleHtml" id=""> <?php $__currentLoopData = $root_categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k => $parent): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <?php if(count($parent->products) > 0): ?> <?php if($parent->name): ?> <?php 
                            $product =  \App\Product::whereHas('product_category_styles', function ($query) use($parent) {
                                                        $query->where('category_id',$parent->id);
                                                        })->where(function ($query) {
                                                                        $query->where('product_group_default', 1)->where('product_group', 1)->orWhere('product_group',  null);
                                                        })->where('category_id',$parent->id)->where('is_active','1')->count();
                            ?> <tr> <th><?php echo e(ucwords($parent->name)); ?> ( <?php echo e($product); ?> Products) </th> </tr> <?php endif; ?> <?php if(!empty($parent->categories)): ?> <?php $__currentLoopData = $parent->categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k => $st): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <?php
                                             
                                             
                                             
                                            $product =  \App\Product::whereHas('product_category_styles', function ($query) use($st,$k) {
                                                        $query->where('category_id',$st->category->categories[$k]->category_id)->where('product_style_id', $st->category->categories[$k]->id);
                                                        })->where(function ($query) {
                                                                        $query->where('product_group_default', 1)->where('product_group', 1)->orWhere('product_group',  null);
                                                        })->where('category_id',$st->category->categories[$k]->category_id)->where('is_active','1')->count();
                                            ?> <tr> <td style="padding-left:45px;"><?php echo e($st->name); ?> (<?php echo e($product); ?>)</td> </tr> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php endif; ?> <?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> </table> <?php endif; ?> </div> <?php if(!request()->all): ?> <div class="text-right"> </div> <?php endif; ?> </div> </div> <div id="ex1" class="modal" style="max-width:800px;"> <div id="GroupMsg"></div> <form role="form" name="groupform" id="groupform" > <?php echo Form::hidden('product_id', null, ['class'=>'form-control','id'=>'product_id']); ?> <?php echo Form::hidden('group_by', null, ['class'=>'form-control','id'=>'group_by']); ?> <div class="card-body"> <div class="form-group"> <?php echo e(Form::checkbox('size', '10', false,['id'=>'sizeGroup','class'=>'Group'])); ?> <label for="size">Size</label> <?php echo e(Form::checkbox('purity', '9', false,['id'=>'purityGroup','class'=>'Group'])); ?> <label for="purity">Purity</label> <div class="row"> <div class="col-sm-12 col-md-12"> <div id="sizeGroupHtml"> <table class="table table-bordered"> <thead> <tr> <th colspan="5"> <center>Product Detail</center> </th> </tr> <tr> <th>#</th> <th>Product</th> <th>Purity</th> <th>Size</th> <th>Default</th> </tr> </thead> <tbody id="GroupValue"> </tbody> </table> </div> </div> </div> </div> <div class="card-footer"> <button type="button" id="saveGroup" class="btn btn-primary">Submit</button> </div> </form> </div>