<?php
 return array (
  'css_front' => NULL,
  'css_front_version' => 1,
  'front_header_full_width' => true,
  'front_footer_full_width' => true,
  'css_manage' => NULL,
  'css_manage_version' => '0.37226800 1582184193',
  'css_front_primary' => '#3f9eef',
  'css_front_secondary' => '#3f9eef',
  'panel_btn_color' => '#3f9eef',
  'panel_btn_hover_color' => '#3f9eef',
  'head_foot_text_color' => '#ffffff',
  'head_foot_icon_color' => '#ffffff',
  'link_hover_color' => '#3f9eef',
  'header_text_color' => '#000000',
  'manage_panel_text_color' => '#ffffff',
  'manage_panel_title_color' => '#ffffff',
  'manage_panel_side_color' => '#333333',
  'manage_panel_main_color' => '#333',
  'manage_panel_hover_color' => '#ff0d0d',
) ;